### ISSUE TITLE
Compile error in latest Xcode  

### ISSUE THREAD

**Issue by zulfeekar** [PureMVC/puremvc-swift-standard-framework#3]
Module file was created by an older version of the compiler.  

<img width="1147" alt="puremvc_error" src="https://cloud.githubusercontent.com/assets/1814993/14654030/0a7836b4-067c-11e6-9c3d-80fb29daa239.png">

**Comment by sshams** [comment]
@zulfeekar That's something that will continue to happen with each updated version of Xcode and Swift. Focus right now is to migrate to more open source friendly Swift Package Manager system and once done repositories will be updated.

Solution for the time being is to download and compile the standard framework itself, generate the .framework library specific to your version of Xcode and replacing the old one linked against the demo.

**Comment by cliffhall** [comment]
Swift 3.0 support has just been added.
